"""update_column_timezone_in_sales

Revision ID: 49efc649fd06
Revises: 9a1408bd8628
Create Date: 2025-06-11 02:19:36.020618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49efc649fd06'
down_revision = '9a1408bd8628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_reps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_reps', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
