"""added_column

Revision ID: 5f634f5c4ca9
Revises: 715390675c71
Create Date: 2025-06-06 19:26:12.446027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f634f5c4ca9'
down_revision = '715390675c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_purpose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('lead_messages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'leads', ['lead_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('reminder_purpose')
    # ### end Alembic commands ###
