"""added email in user

Revision ID: 6be0fc0533da
Revises: 1e102ca80c58
Create Date: 2025-06-18 05:17:28.898727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be0fc0533da'
down_revision = '1e102ca80c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
