"""added massenger access token and instagram access token:


Revision ID: 715390675c71
Revises: e3c433192830
Create Date: 2025-05-29 18:24:16.924332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715390675c71'
down_revision = 'e3c433192830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('messenger_access_token', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('instagram_access_token', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('instagram_access_token')
        batch_op.drop_column('messenger_access_token')

    # ### end Alembic commands ###
