"""adde


Revision ID: 97973503ef4b
Revises: 526120595f48
Create Date: 2025-06-18 05:25:18.941289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97973503ef4b'
down_revision = '526120595f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
